version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Pg@2019"
    ports:
      - "15432:5432"
    volumes:
      - C:/Projects/_github/docker-compose/data/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mateuscviegas@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Pg@2019
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge