version: '3'

services:
  sqlserver:
    container_name: "sqlserver"
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "SQLServer2019"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"